import { z } from "zod";

export const checkInSchema = z.object({
  sleepHours: z.number().min(0).max(24).optional(),
  sleepQuality: z.number().min(1).max(10).optional(),
  restingHeartRate: z.number().optional(),
  bodyweight: z.number().optional(),
  energyLevel: z.number().min(1).max(10).optional(),
  motivation: z.number().min(1).max(10).optional(),
  mood: z.enum(["good", "neutral", "bad", "anxious"]).optional(),
  stressLevel: z.number().min(1).max(10).optional(),
  soreness: z.number().min(1).max(10).optional(),
  hydrationHit: z.boolean().optional(),
  proteinHit: z.boolean().optional(),
  mobilityCompleted: z.boolean().optional(),
  steps: z.number().optional(),
  groinPain: z.number().min(0).max(10).default(0),
  lowerBackPain: z.number().min(0).max(10).default(0),
  shoulderPain: z.number().min(0).max(10).default(0),
  kneePain: z.number().min(0).max(10).default(0),
  hamstringTightness: z.number().min(0).max(10).default(0),
  habits: z.record(z.string(), z.boolean()).optional(),
  habitScore: z.number().optional(),
  notes: z.string().max(500).optional(),
});

export const activitySchema = z.object({
  type: z.enum(["run", "strength", "cycle", "swim", "hike", "yoga", "recovery", "other"]),
  name: z.string().min(1).max(100),
  date: z.string().datetime(),
  duration: z.number().min(1),
  rpe: z.number().min(1).max(10).optional(),
  distance: z.number().optional(),
  elevation: z.number().optional(),
  calories: z.number().optional(),
  avgHr: z.number().optional(),
  maxHr: z.number().optional(),
  cadence: z.number().optional(),
  notes: z.string().max(500).optional(),
  weather: z.record(z.string(), z.unknown()).optional(),
  terrain: z.string().optional(),
  isPublic: z.boolean().optional(),
  exercises: z.array(z.object({
    name: z.string().min(1),
    category: z.string().optional(),
    weight: z.number().optional(),
    sets: z.number().optional(),
    reps: z.number().optional(),
    rpe: z.number().min(1).max(10).optional(),
    tempo: z.string().optional(),
    rest: z.number().optional(),
    painNotes: z.string().optional(),
    fatigueNotes: z.string().optional(),
  })).optional(),
});

export const mealSchema = z.object({
  name: z.string().min(1).max(50),
  date: z.string().datetime(),
  mealType: z.enum(["breakfast", "lunch", "dinner", "snack", "preworkout", "postworkout"]),
  foods: z.array(z.object({
    name: z.string(),
    serving: z.string(),
    calories: z.number(),
    protein: z.number(),
    carbs: z.number(),
    fat: z.number(),
    fiber: z.number().optional(),
  })),
  totalCalories: z.number(),
  totalProtein: z.number(),
  totalCarbs: z.number(),
  totalFat: z.number(),
  totalFiber: z.number().optional(),
  notes: z.string().max(500).optional(),
});

export const profileSchema = z.object({
  height: z.number().optional(),
  weight: z.number().optional(),
  bodyFat: z.number().optional(),
  age: z.number().optional(),
  sex: z.string().optional(),
  restingHR: z.number().optional(),
  vo2Max: z.number().optional(),
  trainingAge: z.number().optional(),
  raceGoal: z.string().optional(),
  raceDistance: z.string().optional(),
  raceDate: z.string().datetime().optional(),
  prs: z.record(z.string(), z.number()).optional(),
  strengthPriorities: z.array(z.string()).optional(),
  endurancePriorities: z.array(z.string()).optional(),
  weeklyAvailability: z.number().optional(),
  recoveryCapacity: z.enum(["low", "medium", "high"]).optional(),
  preferredSplit: z.array(z.string()).optional(),
  equipmentAccess: z.array(z.string()).optional(),
  dietaryPreference: z.string().optional(),
  allergies: z.array(z.string()).optional(),
  targetCalories: z.number().optional(),
  targetProtein: z.number().optional(),
  targetCarbs: z.number().optional(),
  targetFat: z.number().optional(),
  isPublic: z.boolean().optional(),
  bio: z.string().max(300).optional(),
  location: z.string().optional(),
});

export const planSchema = z.object({
  name: z.string().min(1).max(100),
  type: z.enum(["running", "strength", "hybrid", "triathlon", "custom"]),
  phase: z.string().optional(),
  distance: z.string().optional(),
  startDate: z.string().datetime(),
  endDate: z.string().datetime(),
  raceDate: z.string().datetime().optional(),
  totalWeeks: z.number().min(1).max(52),
  weeksPerMesocycle: z.number().min(1).max(8).default(4),
  isAdaptive: z.boolean().optional(),
  autoProgress: z.boolean().optional(),
  baselineFitness: z.record(z.string(), z.unknown()).optional(),
  preferredPaces: z.record(z.string(), z.number()).optional(),
});

export const planDaySchema = z.object({
  date: z.string().datetime(),
  weekNumber: z.number(),
  dayOfWeek: z.number().min(0).max(6),
  workoutType: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  targetDistance: z.number().optional(),
  targetDuration: z.number().optional(),
  targetRPE: z.number().min(1).max(10).optional(),
  targetPace: z.number().optional(),
  paceWindow: z.object({ min: z.string(), max: z.string() }).optional(),
  structure: z.array(z.any()).optional(),
  notes: z.string().optional(),
  cue: z.string().optional(),
});

export const socialPostSchema = z.object({
  text: z.string().max(500).optional(),
  activityId: z.string().optional(),
  images: z.array(z.string()).optional(),
  visibility: z.enum(["public", "friends", "private"]).default("public"),
  tags: z.array(z.string()).optional(),
});

export const socialCommentSchema = z.object({
  postId: z.string(),
  text: z.string().min(1).max(500),
});

export const injurySchema = z.object({
  location: z.string(),
  side: z.enum(["left", "right", "bilateral"]).optional(),
  severity: z.number().min(0).max(10),
  status: z.enum(["active", "monitoring", "recovered"]).default("active"),
  type: z.string().optional(),
  mechanism: z.string().optional(),
  notes: z.string().optional(),
});
